### ISSUE TITLE
Mac Version 1.7

### ISSUE THREAD

**Issue by Clampitts** [EDDiscovery/EDDiscovery-Mac#3] opened 2016-06-10 14:20 UTC
Another great release, but the second zoom in on 2D-Map causes App to crash.  First zoom ok (see grab)
<img width="1492" alt="screen shot 2016-06-10 at 15 18 15" src="https://cloud.githubusercontent.com/assets/19603917/15967246/c528ff0a-2f1e-11e6-8856-dd6662b14d2e.png">

**Comment by noberasco** [comment] 2016-06-10 14:41
Is it always reproducible?
I experienced a couple of crashes during development, but could not reproduce them when trying to to debug them.
Note: you can also zoom in by double-clicking anywhere on the map.

**Comment by Clampitts** [comment] 2016-06-10 16:43
Strange, if I 'double-click' all seems ok, I can then use zoom controls. But if I only use zoom controls, crashes on second zoom in!

**Comment by noberasco** [comment] 2016-07-27 13:54
Is this issue still reproducible?

While I took no steps specific to it, a few versions of EDDiscovery-Mac have been released in the mean while, and the map code has been changed as well. I have been trying to reproducing your issue but had no success so far.

**Comment by Clampitts** [comment] 2016-07-27 14:00
If this is the crash after 2D Zoom, yes – just tested and still crashes

[http://www.risktec.co.uk/Images/RisktecLogo.png]
Tim Arnold | Risktec Solutions Ltd | Wilderspool Park | Greenall's Avenue | Warrington | WA4 6HL | UK
Tel: +44 (0)1925 611200 | Direct: +44 (0)1925 611 217
websitehttp://www.risktec.co.uk/ | consultinghttp://www.risktec.co.uk/consulting.aspx | training & educationhttp://www.risktec.co.uk/training-and-education.aspx | resource solutionshttp://www.risktec.co.uk/resource-solutions.aspx

**Comment by gregmcdougall** [comment] 2016-09-12 22:37
When reproduced in Xcode it's crashing in CartographicOverlayRenderer.m with an EXC_BAD_ACCESS (code=EXC_I386_GPFLT) at CGContextDrawImage(context, theRect, imageRef);

**Comment by noberasco** [comment] 2016-09-15 22:36
@Clampitts, can you give this commit a test run?

I managed to reproduce your issue, but after applying this commit to trigger it I need to really batter the map screen by continuously zooming in/out and panning...

**Comment by noberasco** [comment] 2016-09-20 09:34
Hopefully resolved with 426b0e615d9e3c373d00923e92d0e24c475f5cac

**Closed as completed by noberasco** 2016-09-20 09:34 UTC
Labels: bug
