### ISSUE TITLE
Unable to submit system data to EDSM

### ISSUE THREAD

**Issue by Viking-in-Oz** [EDDiscovery/EDDiscovery-Mac#10] opened 2016-12-13 09:58 UTC
Hi devs,

For a week or more I've been unable to sync data with EDSM.  The only error message in the log window is "ERROR from EDSM: 201 - Missing commander name".

I checked all the system logs through Console.App for anything useful but didn't find anything.

After starting to log this issue, I thought I'd try and run EDDiscovery again and see what happens - now it hangs when trying to sync the jumps with EDSM (after downloading all the new and updated systems and parsing the netLog files).

I left it for 40 minutes, just to see if it would do anything, but no.

I'm happy to try different things, submit log extracts and what-not.

Thanks,
V

**Comment by AnthorNet** [comment] 2016-12-13 09:59
The hanging while syncing logs should be fixed on our side.

**Comment by AnthorNet** [comment] 2016-12-13 15:05
The problem with the distances comes from the App using EDSM without SSL.
That should be fixed by the app author.

**Comment by noberasco** [comment] 2016-12-14 08:00
Thanks for the heads up!
I'll have a look at this issue later today...

**Comment by noberasco** [comment] 2016-12-14 09:38
Hi @Viking-in-Oz,

From what you describe I believe you have an old version of EDDiscovery for Mac installed. Old version take a very long time to parse system updates after downloading.

Make sure you have the latest version of EDDiscovery for mac.
You can download the latest version from here:
https://github.com/EDDiscovery/EDDiscovery-Mac/releases

Regards,
Michele

**Comment by noberasco** [comment] 2016-12-14 09:39
@AnthorNet 

what is the SSL issue you are writing about? I'm trying the latest released version of EDDiscovery for Mac and it seems to work just fine without SSL...

**Comment by Viking-in-Oz** [comment] 2016-12-14 09:50
Hi @noberasco,

I have EDDiscovery-Mac version 1.12 (Build 16) installed. It's been running perfectly for months now, and only started not working a couple of weeks ago.

It's not the downloading system data that's taking a long time, it's the uploading of scanned system data.

***EDIT***
I just fired up EDDiscovery now, and it's working again. What on earth????

Cheers,
V

**Comment by AnthorNet** [comment] 2016-12-14 09:53
@noberasco Every call should be fine (Redirected) except the submit-distances API, which post aren't redirected.
I think ^^

**Comment by noberasco** [comment] 2016-12-16 10:41
Hi @Viking-in-Oz 

Possibly a transient connection issue towards EDSM?
I tried a couple of time but could never reproduce it.

Tentatively closing this issue, feel free to reopen if it happens again.

**Closed as completed by noberasco** 2016-12-16 10:41 UTC
Labels: bug

**Comment by ghost** [comment] 2017-05-20 22:18
I am having this exact issue even on the 1.12 version. Could it be caused by other reasons?

**Comment by Viking-in-Oz** [comment] 2017-05-20 22:22
I've just returned to Elite after a holiday, and the same problem is back again.

My guess is that it's something to do with EDSM, not with EDDiscovery.
